### PR TITLE
Add the ability to change the indent padding when pretty printing

### PR DESCRIPTION
**Pull request by rouzier**

### CODE REVIEW

**Comment by rurban** [comment]
No, we already do this via the option **indent**, so does JSON::PP.

**Comment by rouzier** [comment]
Sorry I did not look at JSON::PP as a reference.
This the option should have been called indent_length.

**Comment by rouzier** [comment]
I updated name of the field to reflect the same option in JSON::PP

**Comment by rouzier** [comment]
Would you want me make another pull request or would prefer to just reopen this one?

**Comment by rurban** [comment]
No, we already have that option :) No need to add it

**Comment by rouzier** [comment]
How do you use it?
Because the number of spaces used for indentation looks hard coded to me.
https://github.com/rurban/Cpanel-JSON-XS/blob/master/XS.xs#L926

**Comment by rurban** [comment]
Oops, you are right, sorry, my mistake. 
indent is only a boolean flag to enable/disable this.
We really need to set the indent_level. 
Can you change the name from pad to indent_level, then it's good.

**Pull request closed without merging**
