### PR TITLE
Encode real core booleans as boolean notation (Fixes #214)

### LINKED ISSUE #214: builtin::true and builtin::false
Perl 5.36 comes with [stable boolean tracking](https://perldoc.perl.org/perldelta#Stable-boolean-tracking). Does this open up any new options for encoding JSON using Cpanel::JSON::XS?

I'm attracted to the prospect of building Perl data structures like `{logging: true}` rather than having to do `{logging: \1}` to get "[logging:true]" in JSON, even though it's more typing.

Here's some test code:

```
use v5.36;
no warnings (qw/experimental::builtin/);
use builtin (qw/is_bool true false/); #  true false/);
use Cpanel::JSON::XS;
my $coder=Cpanel::JSON::XS->new;
$coder->canonical(1);
say $coder->encode({testing=>true,verbose=>false}); # outputs {"testing":1,"verbose":""}
say $coder->encode({testing=>\1,verbose=>\0}); # outputs {"testing":true,"verbose":false}`
```

Is encoding of builtin::true and builtin::false to JSON booleans something that could be enabled in this project? And maybe decoding as well?

I haven't thought carefully about what the implications would be for round-tripping and compatibility with other Perl JSON libraries. JSON:PP has already modified their [is_bool](https://metacpan.org/pod/JSON::PP#JSON::PP::is_bool) method to recognise builtin::true.

```
use v5.36;
no warnings (qw/experimental::builtin/);
use builtin (qw/is_bool true false/);
use JSON::PP ();
use JSON::XS ();
use Cpanel::JSON::XS ();
say JSON::PP::encode_json([true]); # gives: true
say JSON::XS::encode_json([true]); # gives: ["1"]
say Cpanel::JSON::XS::encode_json([true]); # gives: [1]
```

JSON::PP can also be made to decode JSON bool into builtin::true etc:
```
use v5.36;
use JSON::PP ();
use Devel::Peek qw( Dump );

my $coder=JSON::PP->new;
$coder->core_bools(1);
my $data=$coder->decode("[true]"); 
Dump $$data[0];
```
which outputs
```
SV = PVNV(0xaaaae0d029c0) at 0xaaaae0d91c80
  REFCNT = 1
  FLAGS = (IOK,NOK,POK,IsCOW,pIOK,pNOK,pPOK)
  IV = 1
  NV = 1
  PV = 0xaaaab1f00cb8 "1" [BOOL PL_Yes]
  CUR = 1
  LEN = 0
```

JSON::XS can be made to decode in the same way with
`$coder->boolean_values(builtin::false,builtin::true);`

I note that there were discussions about doing something similar for !0 and !1 in #39 and #180 but there didn't seem to be any clear resolution.

### PR DESCRIPTION
**Pull request by leonerd**
A fix for #214.

This PR isn't complete yet though because it causes some other tests related to boolean serialisation to now fail. You'll have to decide if you want to change those tests, or make this behaviour now optional on some configuration flag or somesuch, in order to avoid that.

### CODE REVIEW

**Comment by leonerd** [comment]
Actually that said, it is notable that `JSON::PP` from version 4.16 (or maybe earlier) encodes true directly, without being specially configured:

```
$ eachperl modversion JSON::PP
perl5.36.0: 4.16
perl5.38.0: 4.16
bleadperl: 4.16

$ eachperl -MJSON::PP -E 'say JSON::PP::encode_json([1, "1", builtin::true])'

  --- perl5.36.0 --- 
Built-in function 'builtin::true' is experimental at -e line 1.
[1,"1",true]

  --- perl5.38.0 --- 
Built-in function 'builtin::true' is experimental at -e line 1.
[1,"1",true]

  --- bleadperl --- 
[1,"1",true]
```

**Comment by rurban** [comment]
Looks good to me. The unknown fails seem to be wrong.

**Comment by leonerd** [comment]
> Looks good to me. The unknown fails seem to be wrong.

Latest push attempts to fix those tests while keeping it working on older perls

**Comment by rurban** [comment]
Now just the 9th MOJO test is failing

**Comment by leonerd** [comment]
> Now just the 9th MOJO test is failing

That entire test file seems to be somewhat fragile; it is even commented as being such.

It is using `Test::More::is_deeply` to compare whether the decoded boolean false happens to match `''`.

I'd suggest a more robust test is to check that the received value is booleanly false, numerically zero, and stringily empty in three separate steps:

```perl
ok( !$js->[0], 'decoded Mojo false is false' );
ok( $js->[0] == 0, 'decoded Mojo false is zero' );
ok( $js->[0] eq "", 'decoded Mojo false is empty string' );
```

**Comment by leonerd** [comment]
Actually I've remembered that `cmp_ok` exists so you might prefer to use that instead; up to you.

**Comment by haarg** [comment]
With this change, Cpanel::JSON::XS::is_bool should probably also return true for the core boolean values. JSON::PP does [this](https://metacpan.org/dist/JSON-PP/source/lib/JSON/PP.pm#L1470-1473).

**Comment by rurban** [comment]
> With this change, Cpanel::JSON::XS::is_bool should probably also return true for the core boolean values. JSON::PP does [this](https://metacpan.org/dist/JSON-PP/source/lib/JSON/PP.pm#L1470-1473).

Yes, and couple more minor boolean fixes are pending. Will have more time for this on the weekend

**Comment by leonerd** [comment]
I see this is now merged. Will there be a new CPAN release of the module soon? Ideally I'd like to mention it in my FOSDEM talk, in two weeks time.

**Comment by karenetheridge** [comment]
When this is released I will also update JSON::MaybeXS::is_bool to include the builtins.

**Comment by rurban** [comment]
I need a few more days for the next release

**Pull request merged**
