### PR TITLE
Fix Perl 5.8.0 support

### PR DESCRIPTION
**Pull request by pali**

### CODE REVIEW

**Comment by rurban** [comment]
yeah, 5.8.0 is basically just a broken 5.6.3

**Comment by pali** [comment]
Seems that Travis has timeout problems with it... I will remove it from Travis configuration. But locally it is working.

**Comment by pali** [comment]
Now Travis tests passed. But failing AppVeyor because it cannot download cperl.

**Comment by rurban** [comment]
Yeah, I have to fix the YAML.

**Pull request merged**
