### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by pali**
This pull request fixes different things in tests.

### CODE REVIEW

**Comment by pali** [comment]
@rurban You have broken appveyor testing script.
Instead of `dmake test` it should use `perl -MConfig -e "exec $Config{make}, 'test'"`

**Comment by rurban** [comment]
Well, technically they broke it :) It worked before. Will fix it asap, thanks.

**Comment by rurban** [comment]
PR looks good to me, but I'll smoke them a bit more when I get back home. 
I rebased it with your appveyor fix.

**Comment by pali** [comment]
ok, looks like it passed...

**Comment by rurban** [comment]
Nope, it broke 5.18:

t/25_boolean.t            (Wstat: 512 Tests: 32 Failed: 2)
  Failed tests:  25, 27
  Non-zero exit status: 2

and this failure is with all versions:
t/z_perl_minimum_version.t (Wstat: 256 Tests: 69 Failed: 1)
  Failed test:  42
  Non-zero exit status: 1

**Comment by pali** [comment]
In 5.18 passed all tests: https://travis-ci.org/rurban/Cpanel-JSON-XS/jobs/248380150 including 25_boolean.t.
And I do not see where z_perl_minimum_version.t failed.

**Comment by pali** [comment]
Ah, tests failed under Devel::Cover. But passed without it.

Seems we hit Devel::Cover bug, either https://github.com/pjcj/Devel--Cover/issues/175 or https://github.com/pjcj/Devel--Cover/issues/174. It is not a first time for me that I needed to turn Devel::Cover off as it was changing tests results.

**Comment by rurban** [comment]
I'll be playing with it a bit more when I come back home. Got bad connections in the train

**Comment by pali** [comment]
Any updates? I think we should skip that test when running under Devel::Cover until above bugs are fixed...

**Comment by rurban** [comment]
I'm still trying to fix appveyor, which gives a PASS on failed tests.
Your patch looks mostly fine, and is a vast improvement, sure. Just the boolean tests need a bit of improvements. 
See my smoke-win branch attempts: https://ci.appveyor.com/project/rurban/cpanel-json-xs/build/job/x46ioyk2e88khoci

**Comment by pali** [comment]
Seems that windows ignores return value. In `perldoc -f exec` is written:
> On Windows, only the "exec PROGRAM LIST" indirect object syntax will reliably avoid using the shell

So try: `perl -MConfig -e "exec {$Config{make}} $Config{make}, 'test'"`

**Comment by rurban** [comment]
No. exec is async.
system waits until the end. 
I think the exitlevel 255 is correctly passed back to appveyor's ruby script, (gmake: *** [Makefile:1094: test_dynamic] Error 255
), but then it says Build success.

**Comment by pali** [comment]
Seems you partially right... Now I looked into perl source code.

Perl's exec on windows for non-pseudo-forked child calls WinAPI _execvp(), which spawns new process and exit with 0 itself. Similar to Linux procedure: fork(), exec() in child and exit() in parent.

Therefore you need to use Perl's system which on windows uses WinAPI CreateProcess() and wait for process until finish. After it finish you need to examine $? and properly call Perl's exit.

Something like this should work:
```
perl -MConfig -e "system({$Config{make}} $Config{make}, 'test'); exit(($? < 0 || $? & 127) ? 1 : ($? >> 8));"
```

It is pity that Perl does not implement exec on all platforms to do same thing.

**Comment by pali** [comment]
@rurban have you tried above usage if it really propagates error?

**Comment by pali** [comment]
@rurban ping

**Comment by rurban** [comment]
yes of course. I even tried to create a batch file on fly and call that. It's not the perl exitcode, it's something else.

**Comment by pali** [comment]
From Perl's win32_waitpid implementation it looks like that exit code should be really stored in upper 8 bits of $?. Probably try to run it on Travis as I think it should work.

**Comment by pali** [comment]
Fix for propagating errors is there: https://github.com/rurban/Cpanel-JSON-XS/pull/91

Code from https://github.com/rurban/Cpanel-JSON-XS/pull/88#issuecomment-314202756 is really working.

**Comment by rurban** [comment]
Merged into release 3.0234. Thanks

**Pull request closed without merging**
