### PR TITLE
Fix minimal required version of Math::BigInt and Math::BigFloat modules

### PR DESCRIPTION
**Pull request by pali**

### CODE REVIEW

**Comment by pali** [comment]
I have checked that tests pass with Math::BigFloat 1.16 version without problems..

**Comment by pali** [comment]
Any plans for releasing a new version?

**Comment by rurban** [comment]
Yes, but I'll a bit until your done.

And I will start on the follow up renamed project soon, maybe with simd
extensions and builtin filters.

pali <notifications@github.com> schrieb am Mi., 9. Okt. 2019, 17:02:

**Comment by pali** [comment]
I think I have everything done.

**Pull request merged**
